version: '3'
services:
  node:
    image: "node:19-slim"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./feathers-test/:/app
    ports:
      - 3030:3030
    expose:
      - "3030"
    command: "npm run dev"
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:

